

FROM ubuntu:12.04

MAINTAINER Steven Borrelli <steve@borrelli.org>

ENV NODE_VERSION v0.10.24

RUN apt-get -y install curl unzip

RUN curl -O  http://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-linux-x64.tar.gz

RUN tar -zxvf node-$NODE_VERSION-linux-x64.tar.gz 

RUN ln -s  node-$NODE_VERSION-linux-x64 /node

CMD /node/bin/node



